name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - pip
  - airflow
  - apache-airflow-providers-postgres
  - apache-airflow-providers-amazon
  # - jupyter
  # - mypy
  # - tqdm
  # - pytz
  # - requests
  # - urllib3
  # - tomli
  # - numpy
  # - pandas
  # - pymongo
  # - aiohttp
  # - aiodns
  # - faker
